package com.didi.app.delegate;

import com.component.android.comp_location.GlobalLocationComponent;
import com.didi.android.comp_xbanner.GlobalXBannerComponent;
import com.didi.component.bubbleLayout.BubbleLayoutComponent;
import com.didi.component.cancelbar.CancelComponent;
import com.didi.component.carpool.info.CarpoolInfoComponent;
import com.didi.component.common.base.ComponentType;
import com.didi.component.comp_anycar_append_list.AnyCarAppendListComponent;
import com.didi.component.comp_anycarlist.AnyCarListComponent;
import com.didi.component.comp_config.ConfigComponent;
import com.didi.component.comp_flex.automatic_match.AutomatichMatchComponent;
import com.didi.component.comp_flex.offer_price.OfferFlexPriceComponent;
import com.didi.component.comp_flex.option.FlexOptionComponent;
import com.didi.component.comp_flex.panel.flex.FlexDriverListComponent;
import com.didi.component.comp_form_common.FormCommonComponent;
import com.didi.component.comp_form_common.anycar.AnyCarFormCommonComponent;
import com.didi.component.comp_homecard.HomePanelComponent;
import com.didi.component.comp_homecard.destination.HomeDestinationCardComponent;
import com.didi.component.comp_new_xpanel.NewXpanelComponent;
import com.didi.component.comp_preorderinterceptexpo.PreOrderInterceptComponent;
import com.didi.component.comp_recommend_boarding_point.RecommendBoardingPointComponent;
import com.didi.component.comp_selectseat.SeatSelectComponent;
import com.didi.component.comp_travel_detail_new.TravelDetailNewComponent;
import com.didi.component.comp_xengine.GlobalXEngineComponent;
import com.didi.component.comp_xpanel.GlobalXPanelComponent;
import com.didi.component.company.CompanyComponent;
import com.didi.component.confirmbroadingpoint.ConfirmBroadingPointComponent;
import com.didi.component.confirmupdateaddress.ConfirmUpdateAddressComponent;
import com.didi.component.confirmupdateaddress.OnServiceUpdateAddressComponent;
import com.didi.component.core.ComponentFactory;
import com.didi.component.core.IComponent;
import com.didi.component.deeplink.DeepLinkComponent;
import com.didi.component.dispatchfee.DispatchFeeComponent;
import com.didi.component.driverbar.DriverBarComponent;
import com.didi.component.estimate.EstimateComponent;
import com.didi.component.estimatepass.EstimatePassComponent;
import com.didi.component.evaluate.EvaluateComponent;
import com.didi.component.evaluateentrance.evaluate.FiveStarComponet;
import com.didi.component.evaluatequestion.EvaluateQuestionComponent;
import com.didi.component.expectation.ExpectationComponent;
import com.didi.component.floatbar.FloatBarComponent;
import com.didi.component.groupform.GroupFormComponent;
import com.didi.component.groupform.anycar.AnycarGroupFormComponent;
import com.didi.component.homedestination.HomeDestinationComponent;
import com.didi.component.imentrance.IMEntranceComponent;
import com.didi.component.indriver.InDriverComponent;
import com.didi.component.mapflow.MapFlowComponent;
import com.didi.component.mapflow.traffic.TrafficEventComponent;
import com.didi.component.matchtogo20.ontrip.MTGOnTripComponent;
import com.didi.component.matchtogo20.wait.MTGWaitAcceptComponent;
import com.didi.component.memberpoint.MemberPointComponent;
import com.didi.component.messagebar.MessageBarComponent;
import com.didi.component.newbeecoupon.NewbeeCouponComponent;
import com.didi.component.notalk.NoTalkComponent;
import com.didi.component.openride.NewOpenRideComponent;
import com.didi.component.operationpanel.OperationPanelComponent;
import com.didi.component.pagedata.PageDataComponent;
import com.didi.component.payentrance.NewUIPayEntranceComponent;
import com.didi.component.payentrance.PayEntranceComponent;
import com.didi.component.payment.PayComponent;
import com.didi.component.payway.anycar.PayWayComponent;
import com.didi.component.phoneentrance.PhoneEntranceComponent;
import com.didi.component.pudo.PudoComponent;
import com.didi.component.realtimeprice.RealTimePriceComponent;
import com.didi.component.rideoption.RideOptionComponent;
import com.didi.component.ridestatus.RideStatusComponent;
import com.didi.component.routeguide.RouteGuideComponent;
import com.didi.component.safetoolkit.GlobalJarvisComponent;
import com.didi.component.safetoolkit.GlobalJarvisComponentV2;
import com.didi.component.safetoolkit.GlobalSafeTookKitComponent;
import com.didi.component.savingcenter.SavingCenterComponent;
import com.didi.component.service.ServiceComponent;
import com.didi.component.servicecontrol.nopay.ServiceControlNopayComponent;
import com.didi.component.splitfare.SplitFareComponent;
import com.didi.component.substitute.call.SubstituteComponent;
import com.didi.component.timepicker.TimePickerComponent;
import com.didi.component.travelGroupInfo.TravelGroupInfoComponentV2;
import com.didi.component.traveldetail.TravelDetailComponentV2;
import com.didi.component.unenablecity.UnenableCityComponent;
import com.didi.component.xengineordercompat.GlobalXEngineOrderDetailCompatComponent;

public final class CompRegisterDelegate {
    public static void registerByProduct(String str) {
        ComponentFactory componentFactory = ComponentFactory.get();
        if ("ride".equalsIgnoreCase(str)) {
            componentFactory.register(ComponentType.GLOBAL_XBANNER, (Class<? extends IComponent>) GlobalXBannerComponent.class);
            componentFactory.register(ComponentType.XPANEL_PAX_BOARDING_MODIFY_CARD, (Class<? extends IComponent>) RecommendBoardingPointComponent.class);
            componentFactory.register(ComponentType.ESTIMATE_PASS, (Class<? extends IComponent>) EstimatePassComponent.class);
            componentFactory.register(ComponentType.ROUTE_GUIDE, (Class<? extends IComponent>) RouteGuideComponent.class);
            componentFactory.register(ComponentType.SPLIT_FARE, (Class<? extends IComponent>) SplitFareComponent.class);
            componentFactory.register(ComponentType.DRIVER_BAR, (Class<? extends IComponent>) DriverBarComponent.class);
            componentFactory.register(ComponentType.HOME_ADDRESS_CARD, (Class<? extends IComponent>) HomeDestinationCardComponent.class);
            componentFactory.register(ComponentType.HOME_PANEL, (Class<? extends IComponent>) HomePanelComponent.class);
            componentFactory.register(ComponentType.GROUP_FORM_CONTAINER, (Class<? extends IComponent>) GroupFormComponent.class);
            componentFactory.register(ComponentType.FORM_COMMON_ITEM, (Class<? extends IComponent>) FormCommonComponent.class);
            componentFactory.register(ComponentType.XPANEL, (Class<? extends IComponent>) GlobalXPanelComponent.class);
            componentFactory.register(ComponentType.HOME_DESTINATION, (Class<? extends IComponent>) HomeDestinationComponent.class);
            componentFactory.register("map_flow", (Class<? extends IComponent>) MapFlowComponent.class);
            componentFactory.register(ComponentType.CONFIRM_BROADING_POINT, (Class<? extends IComponent>) ConfirmBroadingPointComponent.class);
            componentFactory.register("estimate", (Class<? extends IComponent>) EstimateComponent.class);
            componentFactory.register(ComponentType.EVALUATE_FIVE_STAR_ENTRANCE, (Class<? extends IComponent>) FiveStarComponet.class);
            componentFactory.register(ComponentType.FLEX_OPTION, (Class<? extends IComponent>) FlexOptionComponent.class);
            componentFactory.register("payment", (Class<? extends IComponent>) PayComponent.class);
            componentFactory.register(ComponentType.FLOAT_BAR, (Class<? extends IComponent>) FloatBarComponent.class);
            componentFactory.register(ComponentType.ON_SERVICE_UPDATE_ADDRESS, (Class<? extends IComponent>) OnServiceUpdateAddressComponent.class);
            componentFactory.register(ComponentType.SAFE_JARVIS, (Class<? extends IComponent>) GlobalJarvisComponent.class);
            componentFactory.register(ComponentType.TRAVEL_GROUP_NEW, (Class<? extends IComponent>) TravelDetailNewComponent.class);
            componentFactory.register(ComponentType.GLOBAL_SAFE_JARVIS, (Class<? extends IComponent>) GlobalJarvisComponentV2.class);
            componentFactory.register("passenger_map_push_card", (Class<? extends IComponent>) TrafficEventComponent.class);
            componentFactory.register(ComponentType.ANY_CAR_APPEND_LIST, (Class<? extends IComponent>) AnyCarAppendListComponent.class);
            componentFactory.register(ComponentType.TRAVEL_GROUP_CARPOOL_INFO, (Class<? extends IComponent>) CarpoolInfoComponent.class);
            componentFactory.register(ComponentType.REAL_TIME_PRICE, (Class<? extends IComponent>) RealTimePriceComponent.class);
            componentFactory.register(ComponentType.TRAVEL_DETAIL_V2, (Class<? extends IComponent>) TravelDetailComponentV2.class);
            componentFactory.register(ComponentType.ANYCAR_PAYWAY, (Class<? extends IComponent>) PayWayComponent.class);
            componentFactory.register(ComponentType.PRE_ORDER_INTERCEPT_EXPO, (Class<? extends IComponent>) PreOrderInterceptComponent.class);
            componentFactory.register(ComponentType.CANCEL_PANEL, (Class<? extends IComponent>) CancelComponent.class);
            componentFactory.register(ComponentType.GLOBAL_X_ENGINE_ORDER_DETAIL_COMPAT, (Class<? extends IComponent>) GlobalXEngineOrderDetailCompatComponent.class);
            componentFactory.register("travel_group_info_v2", (Class<? extends IComponent>) TravelGroupInfoComponentV2.class);
            componentFactory.register(ComponentType.EVALUATE, (Class<? extends IComponent>) EvaluateComponent.class);
            componentFactory.register(ComponentType.BUBBLE_LAYOUT, (Class<? extends IComponent>) BubbleLayoutComponent.class);
            componentFactory.register(ComponentType.SELECT_SEAT, (Class<? extends IComponent>) SeatSelectComponent.class);
            componentFactory.register(ComponentType.ANYCAR_LIST, (Class<? extends IComponent>) AnyCarListComponent.class);
            componentFactory.register(ComponentType.GLOBAL_XENGINE, (Class<? extends IComponent>) GlobalXEngineComponent.class);
            componentFactory.register(ComponentType.SUBSTITUTE_CALL, (Class<? extends IComponent>) SubstituteComponent.class);
            componentFactory.register(ComponentType.SERVICE_CONTROL_NO_PAY, (Class<? extends IComponent>) ServiceControlNopayComponent.class);
            componentFactory.register(ComponentType.PAY_ENTRANCE, (Class<? extends IComponent>) PayEntranceComponent.class);
            componentFactory.register(ComponentType.NEW_XPANEL, (Class<? extends IComponent>) NewXpanelComponent.class);
            componentFactory.register(ComponentType.ANYCAR_FORM_COMMON_ITEM, (Class<? extends IComponent>) AnyCarFormCommonComponent.class);
            componentFactory.register(ComponentType.IM_ENTRANCE, (Class<? extends IComponent>) IMEntranceComponent.class);
            componentFactory.register(ComponentType.ANYCAR_GROUP_FORM_CONTAINER, (Class<? extends IComponent>) AnycarGroupFormComponent.class);
            componentFactory.register(ComponentType.OPERATION_PANEL, (Class<? extends IComponent>) OperationPanelComponent.class);
            componentFactory.register(ComponentType.OFFER_FLEX_PRICE, (Class<? extends IComponent>) OfferFlexPriceComponent.class);
            componentFactory.register(ComponentType.NON_TALKING, (Class<? extends IComponent>) NoTalkComponent.class);
            componentFactory.register(ComponentType.COMPANY, (Class<? extends IComponent>) CompanyComponent.class);
            componentFactory.register(ComponentType.MEMBERPOINR, (Class<? extends IComponent>) MemberPointComponent.class);
            componentFactory.register(ComponentType.DISPATCH_FEE, (Class<? extends IComponent>) DispatchFeeComponent.class);
            componentFactory.register("passenger_newXpanel+bargainingCard_logic+bargaining_card", (Class<? extends IComponent>) InDriverComponent.class);
            componentFactory.register(ComponentType.RESET_LOCATION, (Class<? extends IComponent>) GlobalLocationComponent.class);
            componentFactory.register(ComponentType.RIDE_STATUS, (Class<? extends IComponent>) RideStatusComponent.class);
            componentFactory.register(ComponentType.RIDE_OPTION, (Class<? extends IComponent>) RideOptionComponent.class);
            componentFactory.register(ComponentType.SAFE_TOOLKIT, (Class<? extends IComponent>) GlobalSafeTookKitComponent.class);
            componentFactory.register(ComponentType.SAVING_CENTER, (Class<? extends IComponent>) SavingCenterComponent.class);
            componentFactory.register(ComponentType.PUDO, (Class<? extends IComponent>) PudoComponent.class);
            componentFactory.register(ComponentType.EVALUATE_QUESTION, (Class<? extends IComponent>) EvaluateQuestionComponent.class);
            componentFactory.register(ComponentType.XPANEL_CARPOOL_MATCHONTRIP, (Class<? extends IComponent>) MTGOnTripComponent.class);
            componentFactory.register("deeplink", (Class<? extends IComponent>) DeepLinkComponent.class);
            componentFactory.register(ComponentType.PAYWAY, (Class<? extends IComponent>) com.didi.component.payway.PayWayComponent.class);
            componentFactory.register(ComponentType.RIDE_EXPECTATION, (Class<? extends IComponent>) ExpectationComponent.class);
            componentFactory.register(ComponentType.UNENABLE_CITY, (Class<? extends IComponent>) UnenableCityComponent.class);
            componentFactory.register("message", (Class<? extends IComponent>) MessageBarComponent.class);
            componentFactory.register(ComponentType.EVALUATE_QUESTION_ENTRANCE, (Class<? extends IComponent>) com.didi.component.evaluateentrance.evaluate.EvaluateQuestionComponent.class);
            componentFactory.register(ComponentType.FLEX_LIST, (Class<? extends IComponent>) FlexDriverListComponent.class);
            componentFactory.register(ComponentType.PHONE_ENTRANCE, (Class<? extends IComponent>) PhoneEntranceComponent.class);
            componentFactory.register(ComponentType.PAY_ENTRANCE_NEW_UI, (Class<? extends IComponent>) NewUIPayEntranceComponent.class);
            componentFactory.register(ComponentType.NEW_OPEN_RIDE, (Class<? extends IComponent>) NewOpenRideComponent.class);
            componentFactory.register(ComponentType.FLEX_AUTOMATIC_MATCH_CARD, (Class<? extends IComponent>) AutomatichMatchComponent.class);
            componentFactory.register("service", (Class<? extends IComponent>) ServiceComponent.class);
            componentFactory.register(ComponentType.XPANEL_CARPOOL_MATCHTOGO, (Class<? extends IComponent>) MTGWaitAcceptComponent.class);
            componentFactory.register(ComponentType.NEWBEE_COUPON, (Class<? extends IComponent>) NewbeeCouponComponent.class);
            componentFactory.register(ComponentType.PAGE_DATA, (Class<? extends IComponent>) PageDataComponent.class);
            componentFactory.register("config", (Class<? extends IComponent>) ConfigComponent.class);
            componentFactory.register(ComponentType.CONFIRM_UPDATE_ADDRESS, (Class<? extends IComponent>) ConfirmUpdateAddressComponent.class);
            componentFactory.register(ComponentType.TIME_PICKER, (Class<? extends IComponent>) TimePickerComponent.class);
        }
        System.out.println("Component auto register=========> done");
    }
}
