package com.microblink.blinkbarcode.secured;

import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.Typeface;

/* compiled from: line */
public class llIlIIIIIl {
    private static final float[] IlIIIIIlll = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    private Matrix IIlIIIllIl;
    private Path IlIIlIIIII;
    private Path IlIIlllIIl;
    private Matrix IlIlIlIIlI;
    private Matrix IlIllIlIIl;
    private Path IlIllIlllI;
    private Path IlIlllllII;
    private Matrix IllIIIIllI;
    private Paint IllIIIllII;
    private Path IllIIlIIII;
    private Matrix IlllIIIllI;
    private Matrix lIIIIIlIlI;
    private Path lIIIIIllll;
    private Matrix lIlIIIIlIl;
    private Path lIllIIlIIl;
    private Matrix lIlllIlIlI;
    private Typeface llIIIlllll;
    private Matrix llIIlIIIll;
    private Paint llIIlIIlll;
    private boolean llIIlIlIIl;
    private Matrix llIllIIlll;
    private Matrix lllIIIlIlI;
    private Matrix lllIIlIIlI;
    private Matrix lllIlIlIIl;
    private Path lllllIlIll;

    public void llIIlIlIIl(Canvas canvas, int i, int i2, int i3, int i4) {
        if (!this.llIIlIlIIl) {
            this.llIIlIlIIl = true;
            this.IlIllIlIIl = new Matrix();
            this.IllIIIllII = new Paint();
            this.llIIIlllll = Typeface.create(Typeface.SANS_SERIF, 0);
            this.IllIIIIllI = new Matrix();
            this.llIIlIIlll = new Paint();
            this.lIIIIIllll = new Path();
            this.lllIIIlIlI = new Matrix();
            this.IlIllIlllI = new Path();
            this.lllIlIlIIl = new Matrix();
            this.IllIIlIIII = new Path();
            this.lIIIIIlIlI = new Matrix();
            this.IlIlllllII = new Path();
            this.llIIlIIIll = new Matrix();
            this.IlIIlllIIl = new Path();
            this.llIllIIlll = new Matrix();
            this.lllllIlIll = new Path();
            this.lIlllIlIlI = new Matrix();
            this.lIllIIlIIl = new Path();
            this.lllIIlIIlI = new Matrix();
            this.IlIIlIIIII = new Path();
            this.IlllIIIllI = new Matrix();
            this.IlIlIlIIlI = new Matrix();
        }
        canvas.save();
        canvas.translate((float) i, (float) i2);
        canvas.scale(((float) i3) / 572.0f, ((float) i4) / 571.0f);
        this.IlIllIlIIl.reset();
        this.IlIllIlIIl.preTranslate(-9.0f, -5.865f);
        this.IllIIIllII.reset();
        this.IllIIIllII.setFlags(385);
        this.IllIIIllII.setStyle(Paint.Style.FILL);
        this.IllIIIllII.setTypeface(Typeface.DEFAULT);
        this.IllIIIllII.setColor(-16777216);
        this.IllIIIllII.setTextSize(16.0f);
        this.IllIIIllII.setTypeface(this.llIIIlllll);
        this.IllIIIllII.setStrikeThruText(false);
        this.IllIIIllII.setUnderlineText(false);
        this.IllIIIIllI.reset();
        canvas.concat(this.IllIIIIllI);
        this.lIlIIIIlIl = canvas.getMatrix();
        canvas.save();
        this.llIIlIIlll.reset();
        this.llIIlIIlll.set(this.IllIIIllII);
        this.llIIlIIlll.setColor(-12012824);
        canvas.concat(this.IlIllIlIIl);
        this.IIlIIIllIl = canvas.getMatrix();
        canvas.save();
        this.lIIIIIllll.reset();
        this.lIIIIIllll.moveTo(21.384f, 42.529003f);
        this.lIIIIIllll.lineTo(84.832f, 105.976006f);
        this.lIIIIIllll.lineTo(109.22201f, 81.586006f);
        this.lIIIIIllll.lineTo(45.766003f, 18.139f);
        this.lIIIIIllll.close();
        this.lIIIIIllll.setFillType(Path.FillType.WINDING);
        this.lllIIIlIlI.reset();
        this.IIlIIIllIl.invert(this.lllIIIlIlI);
        this.lllIIIlIlI.preConcat(this.IIlIIIllIl);
        Matrix matrix = this.lllIIIlIlI;
        float[] fArr = IlIIIIIlll;
        matrix.mapPoints(fArr);
        canvas.drawPath(this.lIIIIIllll, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.IlIllIlllI.reset();
        this.IlIllIlllI.moveTo(9.792001f, 308.54703f);
        this.IlIllIlllI.lineTo(99.53f, 308.54703f);
        this.IlIllIlllI.lineTo(99.53f, 274.056f);
        this.IlIllIlllI.lineTo(9.792001f, 274.056f);
        this.IlIllIlllI.close();
        this.IlIllIlllI.setFillType(Path.FillType.WINDING);
        this.lllIlIlIIl.reset();
        this.IIlIIIllIl.invert(this.lllIlIlIIl);
        this.lllIlIlIIl.preConcat(this.IIlIIIllIl);
        this.lllIlIlIIl.mapPoints(fArr);
        canvas.drawPath(this.IlIllIlllI, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.IllIIlIIII.reset();
        this.IllIIlIIII.moveTo(543.01105f, 17.506f);
        this.IllIIlIIII.lineTo(479.56403f, 80.954f);
        this.IllIIlIIII.lineTo(503.946f, 105.344f);
        this.IllIIlIIII.lineTo(567.401f, 41.896004f);
        this.IllIIlIIII.close();
        this.IllIIlIIII.setFillType(Path.FillType.WINDING);
        this.lIIIIIlIlI.reset();
        this.IIlIIIllIl.invert(this.lIIIIIlIlI);
        this.lIIIIIlIlI.preConcat(this.IIlIIIllIl);
        this.lIIIIIlIlI.mapPoints(fArr);
        canvas.drawPath(this.IllIIlIIII, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.IlIlllllII.reset();
        this.IlIlllllII.moveTo(276.98602f, 95.659004f);
        this.IlIlllllII.lineTo(311.484f, 95.659004f);
        this.IlIlllllII.lineTo(311.484f, 5.92f);
        this.IlIlllllII.lineTo(276.98602f, 5.92f);
        this.IlIlllllII.close();
        this.IlIlllllII.setFillType(Path.FillType.WINDING);
        this.llIIlIIIll.reset();
        this.IIlIIIllIl.invert(this.llIIlIIIll);
        this.llIIlIIIll.preConcat(this.IIlIIIllIl);
        this.llIIlIIIll.mapPoints(fArr);
        canvas.drawPath(this.IlIlllllII, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.IlIIlllIIl.reset();
        this.IlIIlllIIl.moveTo(490.35703f, 307.76602f);
        this.IlIIlllIIl.lineTo(580.088f, 307.76602f);
        this.IlIIlllIIl.lineTo(580.088f, 273.27502f);
        this.IlIIlllIIl.lineTo(490.35703f, 273.27502f);
        this.IlIIlllIIl.close();
        this.IlIIlllIIl.setFillType(Path.FillType.WINDING);
        this.llIllIIlll.reset();
        this.IIlIIIllIl.invert(this.llIllIIlll);
        this.llIllIIlll.preConcat(this.IIlIIIllIl);
        this.llIllIIlll.mapPoints(fArr);
        canvas.drawPath(this.IlIIlllIIl, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.lllllIlIll.reset();
        this.lllllIlIll.moveTo(567.40405f, 539.762f);
        this.lllllIlIll.lineTo(503.94803f, 476.31503f);
        this.lllllIlIll.lineTo(479.566f, 500.696f);
        this.lllllIlIll.lineTo(543.01404f, 564.15204f);
        this.lllllIlIll.close();
        this.lllllIlIll.setFillType(Path.FillType.WINDING);
        this.lIlllIlIlI.reset();
        this.IIlIIIllIl.invert(this.lIlllIlIlI);
        this.lIlllIlIlI.preConcat(this.IIlIIIllIl);
        this.lIlllIlIlI.mapPoints(fArr);
        canvas.drawPath(this.lllllIlIll, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.lIllIIlIIl.reset();
        this.lIllIIlIIl.moveTo(45.769f, 564.784f);
        this.lIllIIlIIl.lineTo(109.225006f, 501.329f);
        this.lIllIIlIIl.lineTo(84.83501f, 476.94702f);
        this.lIllIIlIIl.lineTo(21.388f, 540.395f);
        this.lIllIIlIIl.close();
        this.lIllIIlIIl.setFillType(Path.FillType.WINDING);
        this.lllIIlIIlI.reset();
        this.IIlIIIllIl.invert(this.lllIIlIIlI);
        this.lllIIlIIlI.preConcat(this.IIlIIIllIl);
        this.lllIIlIIlI.mapPoints(fArr);
        canvas.drawPath(this.lIllIIlIIl, this.llIIlIIlll);
        canvas.restore();
        canvas.save();
        this.IlIIlIIIII.reset();
        this.IlIIlIIIII.moveTo(277.30002f, 576.361f);
        this.IlIIlIIIII.lineTo(311.798f, 576.361f);
        this.IlIIlIIIII.lineTo(311.798f, 486.62997f);
        this.IlIIlIIIII.lineTo(277.30002f, 486.62997f);
        this.IlIIlIIIII.close();
        this.IlIIlIIIII.setFillType(Path.FillType.WINDING);
        this.IlllIIIllI.reset();
        this.IIlIIIllIl.invert(this.IlllIIIllI);
        this.IlllIIIllI.preConcat(this.IIlIIIllIl);
        this.IlllIIIllI.mapPoints(fArr);
        canvas.drawPath(this.IlIIlIIIII, this.llIIlIIlll);
        canvas.restore();
        this.IlIlIlIIlI.reset();
        this.lIlIIIIlIl.invert(this.IlIlIlIIlI);
        this.IlIlIlIIlI.preConcat(this.IIlIIIllIl);
        this.IlIlIlIIlI.mapPoints(fArr);
        canvas.restore();
        canvas.restore();
    }
}
