package com.threatmetrix.TrustDefender;

import com.didichuxing.mas.sdk.quality.report.utils.Constants;
import com.didichuxing.publicservice.p196db.base.AdDbHelper;

public enum yyyyyq {
    AGENT_LOCALE("alo"),
    APP_HASHES("ih"),
    TIMEZONE_GMT_OFFSET("c"),
    TIMEZONE_DST_DIFF("z"),
    TIMEZONE_NAME("tzd"),
    DEVICE_NAME("name"),
    DEVICE_SIM_IMEI_1("imei1"),
    DEVICE_SIM_IMEI_2("imei2"),
    DEVICE_SIM_STATE_1("sims1"),
    DEVICE_SIM_STATE_2("sims2"),
    DEVICE_HARDWARE_ID("imei"),
    DEVICE_SERIAL("ser"),
    DEVICE_LOCAL_STORAGE_COOKIE("ls"),
    DEVICE_FLASH_COOKIE("fg"),
    DEVICE_DISPLAY_RESOLUTION("f"),
    DEVICE_FINGERPRINT("mdf"),
    APP_SELF_HASH_MD5("ah"),
    APP_SELF_HASH_SHA256("ah2"),
    SELF_HASH_BASE_MODULE("sah"),
    SELF_HASH_DSH_MODULE("mdah"),
    SELF_HASH_AUTH_MODULE("auah"),
    DEVICE_FONT_COUNT("ftsn"),
    DEVICE_FONT_HASH("fts"),
    DEVICE_BOOT_TIME("abt"),
    AGENT_APP_INFO("anv"),
    DEVICE_FREE_SPACE("afs"),
    DEVICE_TOTAL_SPACE("ats"),
    DEVICE_STATE("mds"),
    NETWORK_INFO_BSSID("wbs"),
    NETWORK_INFO_SSID_HASH("wss"),
    NETWORK_INFO_SSID("wssc"),
    NETWORK_INFO_RSSI("wrr"),
    NETWORK_INFO_TYPE("wc"),
    NETWORK_INFO_IPV4("ipv4"),
    NETWORK_INFO_IPV6("ipv6"),
    NETWORK_INFO_MAC("mac"),
    NETWORK_INFO_WFS("wfs"),
    NETWORK_INFO_VPN("vpn"),
    SUBSCRIBER_CELL_INFO("asi"),
    SUBSCRIBER_CELL_ID("aci"),
    ADVERTISING_ID(Constants.JSON_KEY_ANDID),
    SELINUX_MODE("se"),
    SHARED_LIB_INFO("mex2"),
    CONNECTIONS_INFO("nci"),
    APP_INSTALLATION_TIME("apit"),
    APP_MODIFICATION_TIME("amt"),
    SYSTEM_PROXY("spx"),
    NUM_OF_CPU_CORES("nhc"),
    MALICIOUS_APP_STATUS("mlapp"),
    AGENT_OS_VERSION("aov"),
    AGENT_SECURITY_PATCH_LEVEL("aspl"),
    AGENT_LANGUAGE("al"),
    AGENT_BRAND(com.didichuxing.omega.sdk.common.utils.Constants.JSON_KEY_APP_BUILD_VERSION),
    AGENT_DEVICE(AdDbHelper.DB_NAME),
    AGENT_MODEL("am"),
    AGENT_OS("aos"),
    AGENT_CONF_OS("cos"),
    AGENT_TYPE("at"),
    AGENT_VERSION("av"),
    DEVICE_BATTERY_STATUS("btst"),
    DEVICE_ENCRYPTION_STATUS("mex6"),
    DEVICE_DEV_ENABLED_STATUS("dm"),
    TAMPER_CODE_BASE_MODULE("prst"),
    TAMPER_CODE_AUTH_MODULE("autm"),
    TAMPER_CODE_BB_MODULE("bbtm"),
    TAMPER_CODE_DSH_MODULE("mdtm"),
    EM_PATH_COUNT("mr"),
    EM_PATH_STR("mrr"),
    PLUGIN_PATH_STR("pldec1"),
    LOCATION_LATITUDE("tdlat"),
    LOCATION_LONGITUDE("tdlon"),
    LOCATION_ACCURACY("tdlacc"),
    LOCATION_MOCK_STATUS("mlst"),
    ROOT_DETECTION_PATH_COUNT("gr"),
    ROOT_DETECTION_PATH_STR("grr"),
    FIREBASE_PUSH_TOKEN("sa_pt"),
    FINGERPRINT_CAPS("caps"),
    IN_CALL_STATUS("ics"),
    STRONG_ID_SIGNATURE("sid_sig"),
    STRONG_ID_RANDOM("sid_rnd"),
    STRONG_ID_TYPE("sid_type"),
    STRONG_ID_DATE("sid_date"),
    STRONG_ID_KEY("sid_key"),
    STRONG_AUTH_STATUS("sa_st"),
    CRASH_LOG_STRING("crsh");
    
    private final String baa0061a0061a;

    private yyyyyq(String str) {
        this.baa0061a0061a = str;
    }

    public String b00780078x00780078x() {
        return this.baa0061a0061a;
    }
}
