package com.didi.soda.customer.foundation.rpc.entity;

import com.didi.soda.customer.foundation.rpc.entity.topgun.ViewMoreEntity;
import java.util.List;

public class BusinessInfoEntity implements IEntity {
    private static final long serialVersionUID = -8355351095907902352L;
    public ActInfoEntity actInfo;
    public List<PromptEntity> actTips;
    public List<ActTipEntity> actTipsDetails;
    public String adTagDesc;
    public String addr;
    public AnchorInfoEntity anchorInfo;
    public String bUid;
    public String bgImg;
    public List<BusinessOpenDayEntity> bizDayTimeDesc;
    public String bizTimeDesc;
    public List<PromptEntity> bizlineInfo;
    public int businessType = 1;
    public int cHasWine;
    public int cShopStatus;
    public String cShopStatusDesc;
    public String callPhone;
    public int callPhoneProtected;
    public String cartRevision;
    public String cateId;
    public List<PromptEntity> cateTips;
    public String cityId;
    public CollaborationInfo collaborationInfo;
    public String currency;
    public String deliveryDesc;
    public int deliveryPriceAct = -1;
    public String deliveryPriceActDisplay;
    public int deliveryPriceOri = -1;
    public String deliveryPriceOriDisplay;
    public int deliveryTime;
    public int deliveryType;
    public String deliveryTypeDesc;
    public DisclaimerEntity disclaimer;
    public int distance;
    public int exactMatchType;
    public List<PromptEntity> fulfillment;
    public PromptEntity honorInfo;
    public ImageBottomTagEntity imgBottomTag;
    public int isDeliveryPriceAdjusted;
    public int isFavor = -1;
    public int isHideRemark;
    public int isOpenIm;
    public String itemId;
    public List<GoodsItemEntity> itemList;
    public List<GoodsItemEntity> items;
    public double lat;
    public double lng;
    public String logo;
    public String logoImg;
    public String matchItemIds;
    public int maxLevel;
    public BusinessModeInfoEntity modeInfo;
    public int needReloadSubitem;
    public String nextBizTimeDesc;
    public String nextFavDesc;
    public ItemNodeEntity node;
    public int orderWay;
    public String phone;
    public String poi;
    public List<PromptEntity> rating;
    public PromptEntity recInfo;
    public List<PromptEntity> recInfoList;
    public BusinessSearchHotWordEntity recItemSearchWords;
    public List<PromptEntity> recommendTips;
    public String resourceId;
    public String shopAvgPriceDesc;
    public ShopFeatureTipEntity shopFeatureTips;
    public String shopId;
    public String shopImSecret;
    public String shopImg;
    public String shopName;
    public List<BusinessShopPayEntity> shopPayDesc;
    public PromptEntity shopTag;
    public List<PromptEntity> shopTips;
    public BusinessStarRatingEntity starRating;
    public String statusDesc;
    public List<PromptEntity> tags;
    public String url;
    public ViewMoreEntity viewMoreCard;
    public int wineConfirm = -1;
    public String wineConfirmDesc;

    public static class CollaborationInfo implements IEntity {
        private static final long serialVersionUID = -5675400865172870744L;
        public boolean isCollaboration;
        public int sort = 0;
        public int sourcePosition;
    }
}
